import type { Language } from "./translations";

export type AlbionItem = {
	id: string;
	name: { en: string; pt: string };
	categoryId: string; // Links to leaf node in CATEGORY_TREE
	tier: number;
	recipe?: { itemId: string; quantity: number }[];
};

function gen(
	baseId: string,
	nameEn: string,
	namePt: string,
	catId: string,
	tiers: number[],
	resourceId: string,
	quantity: number,
): AlbionItem[] {
	return tiers.map((t) => ({
		id: `T${t}_${baseId}`,
		name: { en: `${nameEn} (T${t})`, pt: `${namePt} (T${t})` },
		categoryId: catId,
		tier: t,
		recipe: [{ itemId: `T${t}_${resourceId}`, quantity }],
	}));
}

function genResource(
	baseId: string,
	nameEn: string,
	namePt: string,
	tiers: number[],
): AlbionItem[] {
	return tiers.map((t) => ({
		id: `T${t}_${baseId}`,
		name: { en: `${nameEn} (T${t})`, pt: `${namePt} (T${t})` },
		categoryId: "resource",
		tier: t,
	}));
}

export const ITEMS: AlbionItem[] = [
	// --- ARMOR ---
	// Cloth Armor
	...gen(
		"HEAD_CLOTH_SET1",
		"Scholar Cowl",
		"Capuz do Estudioso",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),
	...gen(
		"ARMOR_CLOTH_SET1",
		"Scholar Robe",
		"Manto do Estudioso",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		16,
	),
	...gen(
		"SHOES_CLOTH_SET1",
		"Scholar Sandals",
		"Sandálias do Estudioso",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),
	...gen(
		"HEAD_CLOTH_SET2",
		"Cleric Cowl",
		"Capuz do Clérigo",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),
	...gen(
		"ARMOR_CLOTH_SET2",
		"Cleric Robe",
		"Manto do Clérigo",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		16,
	),
	...gen(
		"SHOES_CLOTH_SET2",
		"Cleric Sandals",
		"Sandálias do Clérigo",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),
	...gen(
		"HEAD_CLOTH_SET3",
		"Mage Cowl",
		"Capuz do Mago",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),
	...gen(
		"ARMOR_CLOTH_SET3",
		"Mage Robe",
		"Manto do Mago",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		16,
	),
	...gen(
		"SHOES_CLOTH_SET3",
		"Mage Sandals",
		"Sandálias do Mago",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"CLOTH",
		8,
	),

	// Leather Armor
	...gen(
		"HEAD_LEATHER_SET1",
		"Mercenary Hood",
		"Capuz do Mercenário",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),
	...gen(
		"ARMOR_LEATHER_SET1",
		"Mercenary Jacket",
		"Jaqueta do Mercenário",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		16,
	),
	...gen(
		"SHOES_LEATHER_SET1",
		"Mercenary Shoes",
		"Sapatos do Mercenário",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),
	...gen(
		"HEAD_LEATHER_SET2",
		"Hunter Hood",
		"Capuz do Caçador",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),
	...gen(
		"ARMOR_LEATHER_SET2",
		"Hunter Jacket",
		"Jaqueta do Caçador",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		16,
	),
	...gen(
		"SHOES_LEATHER_SET2",
		"Hunter Shoes",
		"Sapatos do Caçador",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),
	...gen(
		"HEAD_LEATHER_SET3",
		"Assassin Hood",
		"Capuz do Assassino",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),
	...gen(
		"ARMOR_LEATHER_SET3",
		"Assassin Jacket",
		"Jaqueta do Assassino",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		16,
	),
	...gen(
		"SHOES_LEATHER_SET3",
		"Assassin Shoes",
		"Sapatos do Assassino",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"LEATHER",
		8,
	),

	// Plate Armor
	...gen(
		"HEAD_PLATE_SET1",
		"Soldier Helmet",
		"Elmo do Soldado",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"ARMOR_PLATE_SET1",
		"Soldier Armor",
		"Armadura do Soldado",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"SHOES_PLATE_SET1",
		"Soldier Boots",
		"Botas do Soldado",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"HEAD_PLATE_SET2",
		"Knight Helmet",
		"Elmo do Cavaleiro",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"ARMOR_PLATE_SET2",
		"Knight Armor",
		"Armadura do Cavaleiro",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"SHOES_PLATE_SET2",
		"Knight Boots",
		"Botas do Cavaleiro",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"HEAD_PLATE_SET3",
		"Guardian Helmet",
		"Elmo do Guardião",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"ARMOR_PLATE_SET3",
		"Guardian Armor",
		"Armadura do Guardião",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"SHOES_PLATE_SET3",
		"Guardian Boots",
		"Botas do Guardião",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),

	// --- WEAPONS ---
	// Swords
	...gen(
		"MAIN_SWORD",
		"Broadsword",
		"Espada Larga",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_CLAYMORE",
		"Claymore",
		"Claymore",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_DUALSWORD",
		"Dual Swords",
		"Espadas Duplas",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_SCIMITAR_MORGANA",
		"Clarent Blade",
		"Lâmina de Clarent",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	), // Approx
	...gen(
		"2H_CLEAVER_HELL",
		"Carving Sword",
		"Espada Cortante",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	), // Approx
	...gen(
		"2H_SWORD_MORGANA",
		"Galatine Pair",
		"Par de Galatines",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	), // Approx
	...gen(
		"2H_HAMMER_UNDEAD",
		"Kingmaker",
		"Criadora de Reis",
		"sword",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	), // Approx

	// Bows
	...gen("2H_BOW", "Bow", "Arco", "bow", [4, 5, 6, 7, 8], "PLANKS", 32),
	...gen(
		"2H_WARBOW",
		"Warbow",
		"Arco de Guerra",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_LONGBOW",
		"Longbow",
		"Arco Longo",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_LONGBOW_UNDEAD",
		"Whispering Bow",
		"Arco Sussurrante",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_BOW_HELL",
		"Wailing Bow",
		"Arco Plangente",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_BOW_KEEPER",
		"Bow of Badon",
		"Arco de Badon",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_BOW_AVALON",
		"Mistpiercer",
		"Perfuranevoa",
		"bow",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),

	// Axes
	...gen(
		"MAIN_AXE",
		"Battleaxe",
		"Machado de Batalha",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_AXE",
		"Greataxe",
		"Grande Machado",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_HALBERD",
		"Halberd",
		"Alabarda",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_HALBERD_MORGANA",
		"Carrioncaller",
		"Invocador de Carniça",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_SCYTHE_HELL",
		"Infernal Scythe",
		"Foice Infernal",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_AXE_AVALON",
		"Realmbreaker",
		"Quebra-Reinos",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_DUALAXE_KEEPER",
		"Bear Paws",
		"Patas de Urso",
		"axe",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Crossbows
	...gen(
		"2H_CROSSBOW",
		"Crossbow",
		"Besta",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_CROSSBOWLARGE",
		"Heavy Crossbow",
		"Besta Pesada",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"MAIN_1HCROSSBOW",
		"Light Crossbow",
		"Besta Leve",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_REPEATINGCROSSBOW_UNDEAD",
		"Weeping Repeater",
		"Repetidora Chorosa",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_DUALCROSSBOW_HELL",
		"Boltcasters",
		"Lança-virotes",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_CROSSBOW_CANNON_AVALON",
		"Energy Shaper",
		"Moldadora de Energia",
		"crossbow",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Daggers
	...gen(
		"MAIN_DAGGER",
		"Dagger",
		"Adaga",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_DAGGERPAIR",
		"Dagger Pair",
		"Par de Adagas",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_CLAWS",
		"Claws",
		"Garras",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_RAPIER_MORGANA",
		"Bloodletter",
		"Sanguinário",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_IRONGAUNTLETS_HELL",
		"Black Hands",
		"Mãos Negras",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	), // Legacy?
	...gen(
		"2H_DAGGER_KATAR_AVALON",
		"Bridled Fury",
		"Fúria Controlada",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"MAIN_DAGGER_HELL",
		"Demonfang",
		"Presa Demoníaca",
		"dagger",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),

	// Hammers
	...gen(
		"MAIN_HAMMER",
		"Hammer",
		"Martelo",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_POLEHAMMER",
		"Polehammer",
		"Martelo de Guerra",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_HAMMER",
		"Great Hammer",
		"Grande Martelo",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_HAMMER_UNDEAD",
		"Tombhammer",
		"Martelo da Tumba",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_HAMMER_HELL",
		"Forge Hammers",
		"Martelos de Forja",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_HAMMER_AVALON",
		"Grovekeeper",
		"Guardião do Bosque",
		"hammer",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Maces
	...gen("MAIN_MACE", "Mace", "Maça", "mace", [4, 5, 6, 7, 8], "METALBAR", 16),
	...gen(
		"2H_MACE",
		"Heavy Mace",
		"Maça Pesada",
		"mace",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_FLAIL",
		"Morning Star",
		"Maça da Estrela da Manhã",
		"mace",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_MACE_HELL",
		"Incubus Mace",
		"Maça do Íncubo",
		"mace",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_MACE_MORGANA",
		"Camlann Mace",
		"Maça de Camlann",
		"mace",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Spears
	...gen(
		"MAIN_SPEAR",
		"Spear",
		"Lança",
		"spear",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen("2H_SPEAR", "Pike", "Pique", "spear", [4, 5, 6, 7, 8], "METALBAR", 24),
	...gen(
		"2H_GLAIVE",
		"Glaive",
		"Glaive",
		"spear",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_SPEAR_KEEPER",
		"Heron Spear",
		"Lança da Garça",
		"spear",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_SPEAR_HELL",
		"Spirit Hunter",
		"Caçador de Espíritos",
		"spear",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"MAIN_SPEAR_LANCE_AVALON",
		"Daybreaker",
		"Alvorada",
		"spear",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),

	// Fire Staffs
	...gen(
		"MAIN_FIRESTAFF",
		"Fire Staff",
		"Cajado de Fogo",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_FIRESTAFF",
		"Great Fire Staff",
		"Grande Cajado de Fogo",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_INFERNOSTAFF",
		"Infernal Staff",
		"Cajado Infernal",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_FIRESTAFF_KEEPER",
		"Wildfire Staff",
		"Cajado do Fogo Selvagem",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_FIRESTAFF_HELL",
		"Brimstone Staff",
		"Cajado de Enxofre",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_FIRESTAFF_AVALON",
		"Dawnsong",
		"Canção do Amanhecer",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Frost Staffs
	...gen(
		"MAIN_FROSTSTAFF",
		"Frost Staff",
		"Cajado de Gelo",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_FROSTSTAFF",
		"Great Frost Staff",
		"Grande Cajado de Gelo",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_GLACIALSTAFF",
		"Glacial Staff",
		"Cajado Glacial",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_FROSTSTAFF_KEEPER",
		"Hoarfrost Staff",
		"Cajado da Geada",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_ICICLESTAFF_HELL",
		"Icicle Staff",
		"Cajado de Sincelo",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_FROSTSTAFF_AVALON",
		"Chillhowl",
		"Uivo Congelante",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Holy Staffs
	...gen(
		"MAIN_HOLYSTAFF",
		"Holy Staff",
		"Cajado Sagrado",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_HOLYSTAFF",
		"Great Holy Staff",
		"Grande Cajado Sagrado",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_DIVINESTAFF",
		"Divine Staff",
		"Cajado Divino",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_HOLYSTAFF_MORGANA",
		"Lifetouch Staff",
		"Cajado do Toque de Vida",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_HOLYSTAFF_HELL",
		"Fallen Staff",
		"Cajado Caído",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_HOLYSTAFF_AVALON",
		"Hallowfall",
		"Queda Sagrada",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Nature Staffs
	...gen(
		"MAIN_NATURESTAFF",
		"Nature Staff",
		"Cajado da Natureza",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		16,
	),
	...gen(
		"2H_NATURESTAFF",
		"Great Nature Staff",
		"Grande Cajado da Natureza",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		24,
	),
	...gen(
		"2H_WILDSTAFF",
		"Wild Staff",
		"Cajado Silvestre",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		24,
	),
	...gen(
		"MAIN_NATURESTAFF_KEEPER",
		"Druidic Staff",
		"Cajado Druídico",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		16,
	),
	...gen(
		"2H_NATURESTAFF_HELL",
		"Blight Staff",
		"Cajado da Peste",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),
	...gen(
		"2H_NATURESTAFF_AVALON",
		"Ironroot Staff",
		"Cajado de Raiz Férrea",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"PLANKS",
		32,
	),

	// Arcane Staffs
	...gen(
		"MAIN_ARCANESTAFF",
		"Arcane Staff",
		"Cajado Arcano",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_ARCANESTAFF",
		"Great Arcane Staff",
		"Grande Cajado Arcano",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_ENIGMATICSTAFF",
		"Enigmatic Staff",
		"Cajado Enigmático",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_ARCANESTAFF_UNDEAD",
		"Witchwork Staff",
		"Cajado de Feitiçaria",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_ARCANESTAFF_HELL",
		"Occult Staff",
		"Cajado Oculto",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_ARCANESTAFF_AVALON",
		"Evensong",
		"Canção do Crepúsculo",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Cursed Staffs
	...gen(
		"MAIN_CURSEDSTAFF",
		"Cursed Staff",
		"Cajado Maldito",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_CURSEDSTAFF",
		"Great Cursed Staff",
		"Grande Cajado Maldito",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"2H_DEMONICSTAFF",
		"Demonic Staff",
		"Cajado Demoníaco",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		24,
	),
	...gen(
		"MAIN_CURSEDSTAFF_UNDEAD",
		"Lifecurse Staff",
		"Cajado da Maldição de Vida",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		16,
	),
	...gen(
		"2H_CURSEDSTAFF_HELL",
		"Cursed Skull",
		"Crânio Maldito",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),
	...gen(
		"2H_CURSEDSTAFF_AVALON",
		"Shadowcaller",
		"Chamador das Sombras",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"METALBAR",
		32,
	),

	// Off-hands
	...gen(
		"OFF_SHIELD",
		"Shield",
		"Escudo",
		"offhand",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"OFF_BOOK",
		"Tome of Spells",
		"Tomo de Feitiços",
		"offhand",
		[4, 5, 6, 7, 8],
		"METALBAR",
		8,
	),
	...gen(
		"OFF_TORCH",
		"Torch",
		"Tocha",
		"offhand",
		[4, 5, 6, 7, 8],
		"PLANKS",
		8,
	),
	...gen(
		"OFF_HORN_KEEPER",
		"Mistcaller",
		"Chamado da Névoa",
		"offhand",
		[4, 5, 6, 7, 8],
		"PLANKS",
		8,
	),
	...gen(
		"BAG_INSIGHT",
		"Satchel of Insight",
		"Satchel of Insight",
		"bag",
		[4, 5, 6, 7, 8],
		"LEATHER",
		1,
	),
	...gen(
		"MOUNT_SWAMPDRAGON_BATTLE",
		"Flame Basilisk",
		"Flame Basilisk",
		"mount",
		[7],
		"LEATHER",
		1,
	),
	...gen(
		"MOUNT_SWAMPDRAGON_FW_THETFORD",
		"Saddled Swamp Salamander",
		"Saddled Swamp Salamander",
		"mount",
		[5],
		"LEATHER",
		1,
	),
	...gen(
		"MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE",
		"Elite Swamp Salamander",
		"Elite Swamp Salamander",
		"mount",
		[8],
		"LEATHER",
		1,
	),
	...gen(
		"MOUNT_TERRORBIRD_ADC",
		"Saddled Terrorbird",
		"Saddled Terrorbird",
		"mount",
		[7],
		"LEATHER",
		1,
	),
	...gen(
		"MEAL_OMELETTE_AVALON",
		"Avalonian Pork Omelette",
		"Avalonian Pork Omelette",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_OMELETTE",
		"Pork Omelette",
		"Pork Omelette",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_OMELETTE_FISH",
		"Lowriver Crab Omelette",
		"Lowriver Crab Omelette",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen("MEAL_PIE", "Pork Pie", "Pork Pie", "misc", [3, 5, 7], "RESOURCE", 1),
	...gen(
		"MEAL_PIE_FISH",
		"Upland Coldeye Pie",
		"Upland Coldeye Pie",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SALAD",
		"Turnip Salad",
		"Turnip Salad",
		"misc",
		[2, 4, 6],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SALAD_FISH",
		"Shallowshore Squid Salad",
		"Shallowshore Squid Salad",
		"misc",
		[2, 4, 6],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SEAWEEDSALAD",
		"Seaweed Salad",
		"Seaweed Salad",
		"misc",
		[1],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SANDWICH_AVALON",
		"Avalonian Mutton Sandwich",
		"Avalonian Mutton Sandwich",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SANDWICH",
		"Mutton Sandwich",
		"Mutton Sandwich",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SANDWICH_FISH",
		"Thunderfall Lurcher Sandwich",
		"Thunderfall Lurcher Sandwich",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SOUP_FISH",
		"Murkwater Clam Soup",
		"Murkwater Clam Soup",
		"misc",
		[1, 3, 5],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_SOUP",
		"Wheat Soup",
		"Wheat Soup",
		"misc",
		[1, 3, 5],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_STEW_AVALON",
		"Avalonian Mutton Stew",
		"Avalonian Mutton Stew",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_STEW",
		"Mutton Stew",
		"Mutton Stew",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_STEW_FISH",
		"Redspring Eel Stew",
		"Redspring Eel Stew",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_ROAST",
		"Roast Pork",
		"Roast Pork",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"MEAL_ROAST_FISH",
		"Roasted Puremist Snapper",
		"Roasted Puremist Snapper",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_ENERGY",
		"Major Energy Potion",
		"Major Energy Potion",
		"misc",
		[2, 4, 6],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_HEAL",
		"Major Healing Potion",
		"Major Healing Potion",
		"misc",
		[2, 4, 6],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_REVIVE",
		"Major Gigantify Potion",
		"Major Gigantify Potion",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_STONESKIN",
		"Major Resistance Potion",
		"Major Resistance Potion",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_SLOWFIELD",
		"Sticky Potion",
		"Sticky Potion",
		"misc",
		[3, 5, 7],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_COOLDOWN",
		"Major Poison Potion",
		"Major Poison Potion",
		"misc",
		[4, 6, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"POTION_CLEANSE",
		"Invisibility Potion",
		"Invisibility Potion",
		"misc",
		[8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_DUALSCIMITAR_UNDEAD",
		"Galatine Pair",
		"Galatine Pair",
		"sword",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_CLAYMORE_AVALON",
		"Kingmaker",
		"Kingmaker",
		"sword",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MAIN_ROCKMACE_KEEPER",
		"Bedrock Mace",
		"Bedrock Mace",
		"mace",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_DUALMACE_AVALON",
		"Oathkeepers",
		"Oathkeepers",
		"mace",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_DUALHAMMER_HELL",
		"Forge Hammers",
		"Forge Hammers",
		"hammer",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_RAM_KEEPER",
		"Grovekeeper",
		"Grovekeeper",
		"hammer",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_CROSSBOWLARGE_MORGANA",
		"Siegebow",
		"Siegebow",
		"crossbow",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_SET1",
		"Brawler Gloves",
		"Brawler Gloves",
		"misc",
		[3, 4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_SET2",
		"Battle Bracers",
		"Battle Bracers",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_SET3",
		"Spiked Gauntlets",
		"Spiked Gauntlets",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_KEEPER",
		"Ursine Maulers",
		"Ursine Maulers",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_HELL",
		"Hellfire Hands",
		"Hellfire Hands",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_MORGANA",
		"Ravenstrike Cestus",
		"Ravenstrike Cestus",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_KNUCKLES_AVALON",
		"Fists of Avalon",
		"Fists of Avalon",
		"misc",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_HARPOON_HELL",
		"Spirithunter",
		"Spirithunter",
		"spear",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_TRIDENT_UNDEAD",
		"Trinity Spear",
		"Trinity Spear",
		"spear",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_NATURESTAFF_KEEPER",
		"Rampant Staff",
		"Rampant Staff",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MAIN_NATURESTAFF_AVALON",
		"Ironroot Staff",
		"Ironroot Staff",
		"nature_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_CLAWPAIR",
		"Claws",
		"Claws",
		"dagger",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_DUALSICKLE_UNDEAD",
		"Deathgivers",
		"Deathgivers",
		"dagger",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_QUARTERSTAFF",
		"Quarterstaff",
		"Quarterstaff",
		"quarterstaff",
		[3, 4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_DOUBLEBLADEDSTAFF",
		"Double Bladed Staff",
		"Double Bladed Staff",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_IRONCLADEDSTAFF",
		"Iron-clad Staff",
		"Iron-clad Staff",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_COMBATSTAFF_MORGANA",
		"Black Monk Stave",
		"Black Monk Stave",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_TWINSCYTHE_HELL",
		"Soulscythe",
		"Soulscythe",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_ROCKSTAFF_KEEPER",
		"Staff of Balance",
		"Staff of Balance",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_QUARTERSTAFF_AVALON",
		"Grailseeker",
		"Grailseeker",
		"quarterstaff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_INFERNOSTAFF_MORGANA",
		"Blazing Staff",
		"Blazing Staff",
		"fire_staff",
		[4, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_FIRE_RINGPAIR_AVALON",
		"Dawnsong",
		"Dawnsong",
		"fire_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_HOLYSTAFF_UNDEAD",
		"Redemption Staff",
		"Redemption Staff",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MAIN_HOLYSTAFF_AVALON",
		"Hallowfall",
		"Hallowfall",
		"holy_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_ENIGMATICORB_MORGANA",
		"Malevolent Locus",
		"Malevolent Locus",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_ARCANE_RINGPAIR_AVALON",
		"Evensong",
		"Evensong",
		"arcane_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_ICEGAUNTLETS_HELL",
		"Icicle Staff",
		"Icicle Staff",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_ICECRYSTAL_UNDEAD",
		"Permafrost Prism",
		"Permafrost Prism",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MAIN_FROSTSTAFF_AVALON",
		"Chillhowl",
		"Chillhowl",
		"frost_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SKULLORB_HELL",
		"Cursed Skull",
		"Cursed Skull",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_CURSEDSTAFF_MORGANA",
		"Damnation Staff",
		"Damnation Staff",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"MAIN_CURSEDSTAFF_AVALON",
		"Shadowcaller",
		"Shadowcaller",
		"cursed_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_SET1",
		"Prowling Staff",
		"Prowling Staff",
		"shapeshifter_staff",
		[3, 4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_SET2",
		"Rootbound Staff",
		"Rootbound Staff",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_SET3",
		"Primal Staff",
		"Primal Staff",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_MORGANA",
		"Bloodmoon Staff",
		"Bloodmoon Staff",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_HELL",
		"Hellspawn Staff",
		"Hellspawn Staff",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_KEEPER",
		"Earthrune Staff",
		"Earthrune Staff",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"2H_SHAPESHIFTER_AVALON",
		"Lightcaller",
		"Lightcaller",
		"shapeshifter_staff",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_MORGANA",
		"Cultist Robe",
		"Cultist Robe",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_KEEPER",
		"Druid Robe",
		"Druid Robe",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_FEY",
		"Feyscale Robe",
		"Feyscale Robe",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_HELL",
		"Fiend Robe",
		"Fiend Robe",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_AVALON",
		"Robe of Purity",
		"Robe of Purity",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_CLOTH_ROYAL",
		"Royal Robe",
		"Royal Robe",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_HELL",
		"Hellion Jacket",
		"Hellion Jacket",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_AVALON",
		"Jacket of Tenacity",
		"Jacket of Tenacity",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_FEY",
		"Mistwalker Jacket",
		"Mistwalker Jacket",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_ROYAL",
		"Royal Jacket",
		"Royal Jacket",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_UNDEAD",
		"Specter Jacket",
		"Specter Jacket",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_LEATHER_MORGANA",
		"Stalker Jacket",
		"Stalker Jacket",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_HELL",
		"Hellion Hood",
		"Hellion Hood",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_AVALON",
		"Hood of Tenacity",
		"Hood of Tenacity",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_FEY",
		"Mistwalker Hood",
		"Mistwalker Hood",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_ROYAL",
		"Royal Hood",
		"Royal Hood",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_UNDEAD",
		"Specter Hood",
		"Specter Hood",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_LEATHER_MORGANA",
		"Stalker Hood",
		"Stalker Hood",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_HELL",
		"Hellion Shoes",
		"Hellion Shoes",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_FEY",
		"Mistwalker Shoes",
		"Mistwalker Shoes",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_ROYAL",
		"Royal Shoes",
		"Royal Shoes",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_AVALON",
		"Shoes of Tenacity",
		"Shoes of Tenacity",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_UNDEAD",
		"Specter Shoes",
		"Specter Shoes",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_LEATHER_MORGANA",
		"Stalker Shoes",
		"Stalker Shoes",
		"leather_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_AVALON",
		"Armor of Valor",
		"Armor of Valor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_HELL",
		"Demon Armor",
		"Demon Armor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_FEY",
		"Duskweaver Armor",
		"Duskweaver Armor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_UNDEAD",
		"Graveguard Armor",
		"Graveguard Armor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_KEEPER",
		"Judicator Armor",
		"Judicator Armor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"ARMOR_PLATE_ROYAL",
		"Royal Armor",
		"Royal Armor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_HELL",
		"Demon Helmet",
		"Demon Helmet",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_FEY",
		"Duskweaver Helmet",
		"Duskweaver Helmet",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_UNDEAD",
		"Graveguard Helmet",
		"Graveguard Helmet",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_AVALON",
		"Helmet of Valor",
		"Helmet of Valor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_KEEPER",
		"Judicator Helmet",
		"Judicator Helmet",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_PLATE_ROYAL",
		"Royal Helmet",
		"Royal Helmet",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_AVALON",
		"Boots of Valor",
		"Boots of Valor",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_HELL",
		"Demon Boots",
		"Demon Boots",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_FEY",
		"Duskweaver Boots",
		"Duskweaver Boots",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_UNDEAD",
		"Graveguard Boots",
		"Graveguard Boots",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_KEEPER",
		"Judicator Boots",
		"Judicator Boots",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_PLATE_ROYAL",
		"Royal Boots",
		"Royal Boots",
		"plate_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_MORGANA",
		"Cultist Sandals",
		"Cultist Sandals",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_KEEPER",
		"Druid Sandals",
		"Druid Sandals",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_FEY",
		"Feyscale Sandals",
		"Feyscale Sandals",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_HELL",
		"Fiend Sandals",
		"Fiend Sandals",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_ROYAL",
		"Royal Sandals",
		"Royal Sandals",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"SHOES_CLOTH_AVALON",
		"Sandals of Purity",
		"Sandals of Purity",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_AVALON",
		"Cowl of Purity",
		"Cowl of Purity",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_MORGANA",
		"Cultist Cowl",
		"Cultist Cowl",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_KEEPER",
		"Druid Cowl",
		"Druid Cowl",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_FEY",
		"Feyscale Hat",
		"Feyscale Hat",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_HELL",
		"Fiend Cowl",
		"Fiend Cowl",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),
	...gen(
		"HEAD_CLOTH_ROYAL",
		"Royal Cowl",
		"Royal Cowl",
		"cloth_armor",
		[4, 5, 6, 7, 8],
		"RESOURCE",
		1,
	),

	// Accessories
	...gen("BAG", "Bag", "Bolsa", "bag", [4, 5, 6, 7, 8], "LEATHER", 8),
	...gen("CAPE", "Cape", "Capa", "cape", [4, 5, 6, 7, 8], "CLOTH", 8),

	// Resources
	...genResource("LEATHER", "Leather", "Couro", [3, 4, 5, 6, 7, 8]),
	...genResource("METALBAR", "Metal Bar", "Barra de Metal", [3, 4, 5, 6, 7, 8]),
	...genResource("PLANKS", "Planks", "Tábuas", [3, 4, 5, 6, 7, 8]),
	...genResource("CLOTH", "Cloth", "Tecido", [3, 4, 5, 6, 7, 8]),
	...genResource(
		"STONEBLOCK",
		"Stone Block",
		"Bloco de Pedra",
		[3, 4, 5, 6, 7, 8],
	),
	...genResource("HIDE", "Hide", "Pele", [3, 4, 5, 6, 7, 8]),
	...genResource("ORE", "Ore", "Minério", [3, 4, 5, 6, 7, 8]),
	...genResource("WOOD", "Wood", "Madeira", [3, 4, 5, 6, 7, 8]),
	...genResource("FIBER", "Fiber", "Fibra", [3, 4, 5, 6, 7, 8]),
	...genResource("ROCK", "Rock", "Pedra", [3, 4, 5, 6, 7, 8]),
];

// City craft bonuses - which resource types get bonus return in each city
export const CITY_CRAFT_BONUS: Record<string, string[]> = {
	Bridgewatch: [
		"crossbow",
		"dagger",
		"cursed_staff",
		"plate_armor",
		"cloth_shoes",
		"stoneblock",
	],
	Martlock: [
		"axe",
		"quarterstaff",
		"frost_staff",
		"plate_shoes",
		"offhand",
		"planks",
	],
	Lymhurst: [
		"bow",
		"nature_staff",
		"fire_staff",
		"leather_hood",
		"leather_shoes",
		"cloth",
	],
	"Fort Sterling": [
		"hammer",
		"spear",
		"holy_staff",
		"plate_helmet",
		"cloth_armor",
		"metalbar",
	],
	Thetford: [
		"mace",
		"sword",
		"arcane_staff",
		"plate_helmet",
		"leather_armor",
		"leather",
	],
	Caerleon: [],
	Brecilien: [],
};

export function getCategories(_: Language): string[] {
	// Deprecated in favor of categories.ts, but kept for compatibility if needed
	return [...new Set(ITEMS.map((i) => i.categoryId))];
}

export function searchItems(
	query: string,
	lang: "en" | "pt",
	categoryId?: string,
): AlbionItem[] {
	const q = query.toLowerCase();
	let items = ITEMS;

	if (categoryId) {
		items = items.filter((item) => item.categoryId === categoryId);
	}

	return items.filter(
		(item) =>
			item.name[lang].toLowerCase().includes(q) ||
			item.id.toLowerCase().includes(q),
	);
}
