import { CategoryNode, flattenCategories } from "./categories";

export interface AlbionItem {
  id: string;
  name: { en: string; pt: string };
  categoryId: string; // Links to leaf node in CATEGORY_TREE
  tier: number;
  recipe?: { itemId: string; quantity: number }[];
}

function gen(
  baseId: string,
  nameEn: string,
  namePt: string,
  catId: string,
  tiers: number[],
  resourceId: string,
  quantity: number,
): AlbionItem[] {
  return tiers.map((t) => ({
    id: `T${t}_${baseId}`,
    name: { en: `${nameEn} (T${t})`, pt: `${namePt} (T${t})` },
    categoryId: catId,
    tier: t,
    recipe: [{ itemId: `T${t}_${resourceId}`, quantity }],
  }));
}

function genResource(
  baseId: string,
  nameEn: string,
  namePt: string,
  tiers: number[],
): AlbionItem[] {
  return tiers.map((t) => ({
    id: `T${t}_${baseId}`,
    name: { en: `${nameEn} (T${t})`, pt: `${namePt} (T${t})` },
    categoryId: "resource",
    tier: t,
  }));
}

export const ITEMS: AlbionItem[] = [
  // --- ARMOR ---
  // Cloth Armor
  ...gen(
    "HEAD_CLOTH_SET1",
    "Scholar Cowl",
    "Capuz do Estudioso",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),
  ...gen(
    "ARMOR_CLOTH_SET1",
    "Scholar Robe",
    "Manto do Estudioso",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    16,
  ),
  ...gen(
    "SHOES_CLOTH_SET1",
    "Scholar Sandals",
    "Sandálias do Estudioso",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),
  ...gen(
    "HEAD_CLOTH_SET2",
    "Cleric Cowl",
    "Capuz do Clérigo",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),
  ...gen(
    "ARMOR_CLOTH_SET2",
    "Cleric Robe",
    "Manto do Clérigo",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    16,
  ),
  ...gen(
    "SHOES_CLOTH_SET2",
    "Cleric Sandals",
    "Sandálias do Clérigo",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),
  ...gen(
    "HEAD_CLOTH_SET3",
    "Mage Cowl",
    "Capuz do Mago",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),
  ...gen(
    "ARMOR_CLOTH_SET3",
    "Mage Robe",
    "Manto do Mago",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    16,
  ),
  ...gen(
    "SHOES_CLOTH_SET3",
    "Mage Sandals",
    "Sandálias do Mago",
    "cloth_armor",
    [4, 5, 6, 7, 8],
    "CLOTH",
    8,
  ),

  // Leather Armor
  ...gen(
    "HEAD_LEATHER_SET1",
    "Mercenary Hood",
    "Capuz do Mercenário",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),
  ...gen(
    "ARMOR_LEATHER_SET1",
    "Mercenary Jacket",
    "Jaqueta do Mercenário",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    16,
  ),
  ...gen(
    "SHOES_LEATHER_SET1",
    "Mercenary Shoes",
    "Sapatos do Mercenário",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),
  ...gen(
    "HEAD_LEATHER_SET2",
    "Hunter Hood",
    "Capuz do Caçador",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),
  ...gen(
    "ARMOR_LEATHER_SET2",
    "Hunter Jacket",
    "Jaqueta do Caçador",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    16,
  ),
  ...gen(
    "SHOES_LEATHER_SET2",
    "Hunter Shoes",
    "Sapatos do Caçador",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),
  ...gen(
    "HEAD_LEATHER_SET3",
    "Assassin Hood",
    "Capuz do Assassino",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),
  ...gen(
    "ARMOR_LEATHER_SET3",
    "Assassin Jacket",
    "Jaqueta do Assassino",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    16,
  ),
  ...gen(
    "SHOES_LEATHER_SET3",
    "Assassin Shoes",
    "Sapatos do Assassino",
    "leather_armor",
    [4, 5, 6, 7, 8],
    "LEATHER",
    8,
  ),

  // Plate Armor
  ...gen(
    "HEAD_PLATE_SET1",
    "Soldier Helmet",
    "Elmo do Soldado",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "ARMOR_PLATE_SET1",
    "Soldier Armor",
    "Armadura do Soldado",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "SHOES_PLATE_SET1",
    "Soldier Boots",
    "Botas do Soldado",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "HEAD_PLATE_SET2",
    "Knight Helmet",
    "Elmo do Cavaleiro",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "ARMOR_PLATE_SET2",
    "Knight Armor",
    "Armadura do Cavaleiro",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "SHOES_PLATE_SET2",
    "Knight Boots",
    "Botas do Cavaleiro",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "HEAD_PLATE_SET3",
    "Guardian Helmet",
    "Elmo do Guardião",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "ARMOR_PLATE_SET3",
    "Guardian Armor",
    "Armadura do Guardião",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "SHOES_PLATE_SET3",
    "Guardian Boots",
    "Botas do Guardião",
    "plate_armor",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),

  // --- WEAPONS ---
  // Swords
  ...gen(
    "MAIN_SWORD",
    "Broadsword",
    "Espada Larga",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_CLAYMORE",
    "Claymore",
    "Claymore",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_DUALSWORD",
    "Dual Swords",
    "Espadas Duplas",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_SCIMITAR_MORGANA",
    "Clarent Blade",
    "Lâmina de Clarent",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ), // Approx
  ...gen(
    "2H_CLEAVER_HELL",
    "Carving Sword",
    "Espada Cortante",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ), // Approx
  ...gen(
    "2H_SWORD_MORGANA",
    "Galatine Pair",
    "Par de Galatines",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ), // Approx
  ...gen(
    "2H_HAMMER_UNDEAD",
    "Kingmaker",
    "Criadora de Reis",
    "sword",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ), // Approx

  // Bows
  ...gen("2H_BOW", "Bow", "Arco", "bow", [4, 5, 6, 7, 8], "PLANKS", 32),
  ...gen(
    "2H_WARBOW",
    "Warbow",
    "Arco de Guerra",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_LONGBOW",
    "Longbow",
    "Arco Longo",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_LONGBOW_UNDEAD",
    "Whispering Bow",
    "Arco Sussurrante",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_BOW_HELL",
    "Wailing Bow",
    "Arco Plangente",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_BOW_KEEPER",
    "Bow of Badon",
    "Arco de Badon",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_BOW_AVALON",
    "Mistpiercer",
    "Perfuranevoa",
    "bow",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),

  // Axes
  ...gen(
    "MAIN_AXE",
    "Battleaxe",
    "Machado de Batalha",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_AXE",
    "Greataxe",
    "Grande Machado",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_HALBERD",
    "Halberd",
    "Alabarda",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_HALBERD_MORGANA",
    "Carrioncaller",
    "Invocador de Carniça",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_SCYTHE_HELL",
    "Infernal Scythe",
    "Foice Infernal",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_AXE_AVALON",
    "Realmbreaker",
    "Quebra-Reinos",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "MAIN_AXE_KEEPER",
    "Bear Paws",
    "Patas de Urso",
    "axe",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Crossbows
  ...gen(
    "2H_CROSSBOW",
    "Crossbow",
    "Besta",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_CROSSBOWLARGE",
    "Heavy Crossbow",
    "Besta Pesada",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "MAIN_1HCROSSBOW",
    "Light Crossbow",
    "Besta Leve",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_REPEATINGCROSSBOW_UNDEAD",
    "Weeping Repeater",
    "Repetidora Chorosa",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_DUALCROSSBOW_HELL",
    "Boltcasters",
    "Lança-virotes",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_CROSSBOW_CANNON_AVALON",
    "Energy Shaper",
    "Moldadora de Energia",
    "crossbow",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Daggers
  ...gen(
    "MAIN_DAGGER",
    "Dagger",
    "Adaga",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_DAGGERPAIR",
    "Dagger Pair",
    "Par de Adagas",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_CLAWS",
    "Claws",
    "Garras",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_RAPIER_MORGANA",
    "Bloodletter",
    "Sanguinário",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_IRONGAUNTLETS_HELL",
    "Black Hands",
    "Mãos Negras",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ), // Legacy?
  ...gen(
    "2H_DAGGER_KATAR_AVALON",
    "Bridled Fury",
    "Fúria Controlada",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "MAIN_DAGGER_HELL",
    "Demonfang",
    "Presa Demoníaca",
    "dagger",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),

  // Hammers
  ...gen(
    "MAIN_HAMMER",
    "Hammer",
    "Martelo",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_POLEHAMMER",
    "Polehammer",
    "Martelo de Guerra",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_HAMMER",
    "Great Hammer",
    "Grande Martelo",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_HAMMER_UNDEAD",
    "Tombhammer",
    "Martelo da Tumba",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_HAMMER_HELL",
    "Forge Hammers",
    "Martelos de Forja",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_HAMMER_AVALON",
    "Grovekeeper",
    "Guardião do Bosque",
    "hammer",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Maces
  ...gen("MAIN_MACE", "Mace", "Maça", "mace", [4, 5, 6, 7, 8], "METALBAR", 16),
  ...gen(
    "2H_MACE",
    "Heavy Mace",
    "Maça Pesada",
    "mace",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_FLAIL",
    "Morning Star",
    "Maça da Estrela da Manhã",
    "mace",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_MACE_HELL",
    "Incubus Mace",
    "Maça do Íncubo",
    "mace",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_MACE_MORGANA",
    "Camlann Mace",
    "Maça de Camlann",
    "mace",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Spears
  ...gen(
    "MAIN_SPEAR",
    "Spear",
    "Lança",
    "spear",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen("2H_SPEAR", "Pike", "Pique", "spear", [4, 5, 6, 7, 8], "METALBAR", 24),
  ...gen(
    "2H_GLAIVE",
    "Glaive",
    "Glaive",
    "spear",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_SPEAR_KEEPER",
    "Heron Spear",
    "Lança da Garça",
    "spear",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_SPEAR_HELL",
    "Spirit Hunter",
    "Caçador de Espíritos",
    "spear",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "MAIN_SPEAR_LANCE_AVALON",
    "Daybreaker",
    "Alvorada",
    "spear",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),

  // Fire Staffs
  ...gen(
    "MAIN_FIRESTAFF",
    "Fire Staff",
    "Cajado de Fogo",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_FIRESTAFF",
    "Great Fire Staff",
    "Grande Cajado de Fogo",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_INFERNOSTAFF",
    "Infernal Staff",
    "Cajado Infernal",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_FIRESTAFF_KEEPER",
    "Wildfire Staff",
    "Cajado do Fogo Selvagem",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_FIRESTAFF_HELL",
    "Brimstone Staff",
    "Cajado de Enxofre",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_FIRESTAFF_AVALON",
    "Dawnsong",
    "Canção do Amanhecer",
    "fire_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Frost Staffs
  ...gen(
    "MAIN_FROSTSTAFF",
    "Frost Staff",
    "Cajado de Gelo",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_FROSTSTAFF",
    "Great Frost Staff",
    "Grande Cajado de Gelo",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_GLACIALSTAFF",
    "Glacial Staff",
    "Cajado Glacial",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_FROSTSTAFF_KEEPER",
    "Hoarfrost Staff",
    "Cajado da Geada",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_ICICLESTAFF_HELL",
    "Icicle Staff",
    "Cajado de Sincelo",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_FROSTSTAFF_AVALON",
    "Chillhowl",
    "Uivo Congelante",
    "frost_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Holy Staffs
  ...gen(
    "MAIN_HOLYSTAFF",
    "Holy Staff",
    "Cajado Sagrado",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_HOLYSTAFF",
    "Great Holy Staff",
    "Grande Cajado Sagrado",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_DIVINESTAFF",
    "Divine Staff",
    "Cajado Divino",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_HOLYSTAFF_MORGANA",
    "Lifetouch Staff",
    "Cajado do Toque de Vida",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_HOLYSTAFF_HELL",
    "Fallen Staff",
    "Cajado Caído",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_HOLYSTAFF_AVALON",
    "Hallowfall",
    "Queda Sagrada",
    "holy_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Nature Staffs
  ...gen(
    "MAIN_NATURESTAFF",
    "Nature Staff",
    "Cajado da Natureza",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    16,
  ),
  ...gen(
    "2H_NATURESTAFF",
    "Great Nature Staff",
    "Grande Cajado da Natureza",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    24,
  ),
  ...gen(
    "2H_WILDSTAFF",
    "Wild Staff",
    "Cajado Silvestre",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    24,
  ),
  ...gen(
    "MAIN_NATURESTAFF_KEEPER",
    "Druidic Staff",
    "Cajado Druídico",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    16,
  ),
  ...gen(
    "2H_NATURESTAFF_HELL",
    "Blight Staff",
    "Cajado da Peste",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),
  ...gen(
    "2H_NATURESTAFF_AVALON",
    "Ironroot Staff",
    "Cajado de Raiz Férrea",
    "nature_staff",
    [4, 5, 6, 7, 8],
    "PLANKS",
    32,
  ),

  // Arcane Staffs
  ...gen(
    "MAIN_ARCANESTAFF",
    "Arcane Staff",
    "Cajado Arcano",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_ARCANESTAFF",
    "Great Arcane Staff",
    "Grande Cajado Arcano",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_ENIGMATICSTAFF",
    "Enigmatic Staff",
    "Cajado Enigmático",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_ARCANESTAFF_UNDEAD",
    "Witchwork Staff",
    "Cajado de Feitiçaria",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_ARCANESTAFF_HELL",
    "Occult Staff",
    "Cajado Oculto",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_ARCANESTAFF_AVALON",
    "Evensong",
    "Canção do Crepúsculo",
    "arcane_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Cursed Staffs
  ...gen(
    "MAIN_CURSEDSTAFF",
    "Cursed Staff",
    "Cajado Maldito",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_CURSEDSTAFF",
    "Great Cursed Staff",
    "Grande Cajado Maldito",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "2H_DEMONICSTAFF",
    "Demonic Staff",
    "Cajado Demoníaco",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    24,
  ),
  ...gen(
    "MAIN_CURSEDSTAFF_UNDEAD",
    "Lifecurse Staff",
    "Cajado da Maldição de Vida",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    16,
  ),
  ...gen(
    "2H_CURSEDSTAFF_HELL",
    "Cursed Skull",
    "Crânio Maldito",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),
  ...gen(
    "2H_CURSEDSTAFF_AVALON",
    "Shadowcaller",
    "Chamador das Sombras",
    "cursed_staff",
    [4, 5, 6, 7, 8],
    "METALBAR",
    32,
  ),

  // Off-hands
  ...gen(
    "OFF_SHIELD",
    "Shield",
    "Escudo",
    "offhand",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "OFF_BOOK",
    "Tome of Spells",
    "Tomo de Feitiços",
    "offhand",
    [4, 5, 6, 7, 8],
    "METALBAR",
    8,
  ),
  ...gen(
    "OFF_TORCH",
    "Torch",
    "Tocha",
    "offhand",
    [4, 5, 6, 7, 8],
    "PLANKS",
    8,
  ),
  ...gen(
    "OFF_HORN_KEEPER",
    "Mistcaller",
    "Chamado da Névoa",
    "offhand",
    [4, 5, 6, 7, 8],
    "PLANKS",
    8,
  ),

  // Accessories
  ...gen("BAG", "Bag", "Bolsa", "bag", [4, 5, 6, 7, 8], "LEATHER", 8),
  ...gen("CAPE", "Cape", "Capa", "cape", [4, 5, 6, 7, 8], "CLOTH", 8),

  // Resources
  ...genResource("LEATHER", "Leather", "Couro", [3, 4, 5, 6, 7, 8]),
  ...genResource("METALBAR", "Metal Bar", "Barra de Metal", [3, 4, 5, 6, 7, 8]),
  ...genResource("PLANKS", "Planks", "Tábuas", [3, 4, 5, 6, 7, 8]),
  ...genResource("CLOTH", "Cloth", "Tecido", [3, 4, 5, 6, 7, 8]),
  ...genResource(
    "STONEBLOCK",
    "Stone Block",
    "Bloco de Pedra",
    [3, 4, 5, 6, 7, 8],
  ),
  ...genResource("HIDE", "Hide", "Pele", [3, 4, 5, 6, 7, 8]),
  ...genResource("ORE", "Ore", "Minério", [3, 4, 5, 6, 7, 8]),
  ...genResource("WOOD", "Wood", "Madeira", [3, 4, 5, 6, 7, 8]),
  ...genResource("FIBER", "Fiber", "Fibra", [3, 4, 5, 6, 7, 8]),
  ...genResource("ROCK", "Rock", "Pedra", [3, 4, 5, 6, 7, 8]),
];

// City craft bonuses - which resource types get bonus return in each city
export const CITY_CRAFT_BONUS: Record<string, string[]> = {
  Bridgewatch: [
    "crossbow",
    "dagger",
    "cursed_staff",
    "plate_armor",
    "cloth_shoes",
    "stoneblock",
  ],
  Martlock: [
    "axe",
    "quarterstaff",
    "frost_staff",
    "plate_shoes",
    "offhand",
    "planks",
  ],
  Lymhurst: [
    "bow",
    "nature_staff",
    "fire_staff",
    "leather_hood",
    "leather_shoes",
    "cloth",
  ],
  "Fort Sterling": [
    "hammer",
    "spear",
    "holy_staff",
    "plate_helmet",
    "cloth_armor",
    "metalbar",
  ],
  Thetford: [
    "mace",
    "sword",
    "arcane_staff",
    "plate_helmet",
    "leather_armor",
    "leather",
  ],
  Caerleon: [],
  Brecilien: [],
};

export function getCategories(lang: "en" | "pt"): string[] {
  // Deprecated in favor of categories.ts, but kept for compatibility if needed
  return [...new Set(ITEMS.map((i) => i.categoryId))];
}

export function searchItems(
  query: string,
  lang: "en" | "pt",
  categoryId?: string,
): AlbionItem[] {
  const q = query.toLowerCase();
  let items = ITEMS;

  if (categoryId) {
    items = items.filter((item) => item.categoryId === categoryId);
  }

  return items.filter(
    (item) =>
      item.name[lang].toLowerCase().includes(q) ||
      item.id.toLowerCase().includes(q),
  );
}
